In [102]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from functools import reduce
%matplotlib inline

In [103]:
#Import OANDA Data
df_eurusd1 = pd.read_csv('Data_Investingcom/EUR_USD_1')
df_eurusd2 = pd.read_csv('Data_Investingcom/EUR_USD_2')
df_eurusd3 = pd.read_csv('Data_Investingcom/EUR_USD_3')

In [104]:
print(df_eurusd1)
print(df_eurusd2)
print(df_eurusd3)

              Date   Price    Open    High     Low Change %
0     Nov 21, 2018  1.1371  1.1372  1.1410  1.1366   -0.01%
1     Nov 20, 2018  1.1372  1.1455  1.1472  1.1359   -0.71%
2     Nov 19, 2018  1.1453  1.1403  1.1467  1.1393    0.29%
3     Nov 16, 2018  1.1420  1.1330  1.1423  1.1320    0.81%
4     Nov 15, 2018  1.1328  1.1309  1.1364  1.1271    0.16%
5     Nov 14, 2018  1.1310  1.1290  1.1349  1.1262    0.17%
6     Nov 13, 2018  1.1291  1.1219  1.1296  1.1216    0.65%
7     Nov 12, 2018  1.1218  1.1331  1.1333  1.1214   -1.04%
8     Nov 09, 2018  1.1336  1.1364  1.1371  1.1315   -0.24%
9     Nov 08, 2018  1.1363  1.1425  1.1448  1.1352   -0.55%
10    Nov 07, 2018  1.1426  1.1427  1.1502  1.1395   -0.01%
11    Nov 06, 2018  1.1427  1.1406  1.1440  1.1389    0.18%
12    Nov 05, 2018  1.1407  1.1391  1.1425  1.1356    0.18%
13    Nov 02, 2018  1.1387  1.1408  1.1458  1.1372   -0.19%
14    Nov 01, 2018  1.1409  1.1311  1.1426  1.1306    0.86%
15    Oct 31, 2018  1.1312  1.1345  1.1363  1.1301   -0.28%
16    Oct 30, 2018  1.1344  1.1372  1.1387  1.1338   -0.25%
17    Oct 29, 2018  1.1373  1.1408  1.1418  1.1361   -0.26%
18    Oct 26, 2018  1.1403  1.1376  1.1422  1.1334    0.24%
19    Oct 25, 2018  1.1376  1.1392  1.1434  1.1355   -0.14%
20    Oct 24, 2018  1.1392  1.1470  1.1477  1.1378   -0.69%
21    Oct 23, 2018  1.1471  1.1466  1.1495  1.1438    0.05%
22    Oct 22, 2018  1.1465  1.1507  1.1552  1.1455   -0.43%
23    Oct 19, 2018  1.1515  1.1451  1.1536  1.1433    0.54%
24    Oct 18, 2018  1.1453  1.1500  1.1528  1.1448   -0.42%
25    Oct 17, 2018  1.1501  1.1575  1.1585  1.1495   -0.64%
26    Oct 16, 2018  1.1575  1.1580  1.1623  1.1564   -0.03%
27    Oct 15, 2018  1.1579  1.1559  1.1608  1.1537    0.14%
28    Oct 12, 2018  1.1563  1.1592  1.1611  1.1534   -0.27%
29    Oct 11, 2018  1.1594  1.1519  1.1600  1.1517    0.64%
...            ...     ...     ...     ...     ...      ...
4950  Dec 01, 1999  1.0080  1.0095  1.0130  1.0046   -0.11%
4951  Nov 30, 1999  1.0091  1.0097  1.0147  1.0043   -0.04%
4952  Nov 29, 1999  1.0095  1.0156  1.0202  1.0036   -0.70%
4953  Nov 26, 1999  1.0166  1.0181  1.0198  1.0076   -0.24%
4954  Nov 25, 1999  1.0190  1.0182  1.0223  1.0167   -0.01%
4955  Nov 24, 1999  1.0191  1.0286  1.0287  1.0154   -0.89%
4956  Nov 23, 1999  1.0282  1.0316  1.0335  1.0253   -0.36%
4957  Nov 22, 1999  1.0319  1.0302  1.0345  1.0285    0.12%
4958  Nov 19, 1999  1.0307  1.0303  1.0339  1.0246    0.10%
4959  Nov 18, 1999  1.0297  1.0412  1.0438  1.0257   -1.10%
4960  Nov 17, 1999  1.0412  1.0305  1.0445  1.0296    1.11%
4961  Nov 16, 1999  1.0298  1.0333  1.0359  1.0290   -0.32%
4962  Nov 15, 1999  1.0331  1.0322  1.0343  1.0295    0.12%
4963  Nov 12, 1999  1.0319  1.0405  1.0415  1.0287   -0.87%
4964  Nov 11, 1999  1.0410  1.0448  1.0452  1.0389   -0.36%
4965  Nov 10, 1999  1.0448  1.0405  1.0454  1.0384    0.41%
4966  Nov 09, 1999  1.0405  1.0386  1.0435  1.0362    0.15%
4967  Nov 08, 1999  1.0389  1.0446  1.0463  1.0345   -0.25%
4968  Nov 05, 1999  1.0415  1.0384  1.0438  1.0358    0.35%
4969  Nov 04, 1999  1.0379  1.0486  1.0543  1.0349   -1.00%
4970  Nov 03, 1999  1.0484  1.0525  1.0532  1.0455   -0.33%
4971  Nov 02, 1999  1.0519  1.0519  1.0557  1.0483    0.06%
4972  Nov 01, 1999  1.0513  1.0549  1.0594  1.0481   -0.36%
4973  Oct 29, 1999  1.0551  1.0524  1.0560  1.0433    0.28%
4974  Oct 28, 1999  1.0522  1.0524  1.0546  1.0469    0.02%
4975  Oct 27, 1999  1.0520  1.0596  1.0642  1.0482   -0.70%
4976  Oct 26, 1999  1.0594  1.0676  1.0695  1.0561   -0.78%
4977  Oct 25, 1999  1.0677  1.0688  1.0704  1.0633   -0.08%
4978  Oct 22, 1999  1.0686  1.0804  1.0814  1.0652   -1.07%
4979  Oct 21, 1999  1.0802  1.0766  1.0835  1.0755    0.49%

[4980 rows x 6 columns]
              Date   Price    Open    High     Low Change %
0     Oct 20, 1999  1.0749  1.0829  1.0842  1.0730   -0.72%
1     Oct 19, 1999  1.0827  1.0819  1.0852  1.0774    0.10%
2     Oct 18, 1999  1.0816  1.0900  1.0905  1.0802   -0.64%
3     Oct 15, 1999  1.0886  1.0776  1.0913  1.0766    1.02%
4     Oct 14, 1999  1.0776  1.0811  1.0831  1.0750   -0.30%
5     Oct 13, 1999  1.0808  1.0772  1.0817  1.0734    0.33%
6     Oct 12, 1999  1.0772  1.0633  1.0774  1.0629    1.30%
7     Oct 11, 1999  1.0634  1.0615  1.0657  1.0609   -0.01%
8     Oct 08, 1999  1.0635  1.0712  1.0721  1.0603   -0.74%
9     Oct 07, 1999  1.0714  1.0688  1.0750  1.0656    0.22%
10    Oct 06, 1999  1.0690  1.0730  1.0780  1.0676   -0.45%
11    Oct 05, 1999  1.0738  1.0735  1.0760  1.0666    0.02%
12    Oct 04, 1999  1.0736  1.0710  1.0776  1.0689    0.15%
13    Oct 01, 1999  1.0720  1.0678  1.0770  1.0667    0.34%
14    Sep 30, 1999  1.0684  1.0640  1.0702  1.0604    0.39%
15    Sep 29, 1999  1.0642  1.0520  1.0657  1.0513    1.12%
16    Sep 28, 1999  1.0524  1.0460  1.0571  1.0441    0.59%
17    Sep 27, 1999  1.0462  1.0438  1.0479  1.0392    0.22%
18    Sep 24, 1999  1.0439  1.0510  1.0546  1.0422   -0.63%
19    Sep 23, 1999  1.0505  1.0433  1.0509  1.0392    0.62%
20    Sep 22, 1999  1.0440  1.0492  1.0543  1.0408   -0.51%
21    Sep 21, 1999  1.0494  1.0362  1.0503  1.0362    1.33%
22    Sep 20, 1999  1.0356  1.0417  1.0452  1.0347   -0.66%
23    Sep 17, 1999  1.0425  1.0391  1.0427  1.0360    0.38%
24    Sep 16, 1999  1.0386  1.0406  1.0472  1.0346   -0.20%
25    Sep 15, 1999  1.0407  1.0357  1.0423  1.0284    0.48%
26    Sep 14, 1999  1.0357  1.0418  1.0444  1.0318   -0.65%
27    Sep 13, 1999  1.0425  1.0356  1.0429  1.0299    0.61%
28    Sep 10, 1999  1.0362  1.0539  1.0564  1.0349   -1.72%
29    Sep 09, 1999  1.0543  1.0598  1.0636  1.0524   -0.53%
...            ...     ...     ...     ...     ...      ...
4868  Dec 01, 1980  1.3425  1.3425  1.3425  1.3425   -0.55%
4869  Nov 28, 1980  1.3499  1.3499  1.3499  1.3499   -0.03%
4870  Nov 27, 1980  1.3503  1.3503  1.3503  1.3503   -0.21%
4871  Nov 26, 1980  1.3532  1.3532  1.3532  1.3532   -0.35%
4872  Nov 25, 1980  1.3580  1.3580  1.3580  1.3580    0.07%
4873  Nov 24, 1980  1.3570  1.3570  1.3570  1.3570    0.16%
4874  Nov 21, 1980  1.3548  1.3548  1.3548  1.3548   -0.34%
4875  Nov 20, 1980  1.3594  1.3594  1.3594  1.3594   -0.45%
4876  Nov 19, 1980  1.3656  1.3656  1.3656  1.3656    0.46%
4877  Nov 18, 1980  1.3594  1.3594  1.3594  1.3594    0.67%
4878  Nov 17, 1980  1.3503  1.3503  1.3503  1.3503   -1.24%
4879  Nov 14, 1980  1.3672  1.3672  1.3672  1.3672   -0.62%
4880  Nov 13, 1980  1.3757  1.3757  1.3757  1.3757    0.04%
4881  Nov 12, 1980  1.3751  1.3751  1.3751  1.3751   -0.54%
4882  Nov 11, 1980  1.3826  1.3826  1.3826  1.3826    1.24%
4883  Nov 10, 1980  1.3656  1.3656  1.3656  1.3656    2.04%
4884  Nov 07, 1980  1.3383  1.3383  1.3383  1.3383   -0.50%
4885  Nov 06, 1980  1.3450  1.3450  1.3450  1.3450   -0.23%
4886  Nov 05, 1980  1.3481  1.3481  1.3481  1.3481   -1.24%
4887  Nov 04, 1980  1.3650  1.3650  1.3650  1.3650    0.11%
4888  Nov 03, 1980  1.3635  1.3635  1.3635  1.3635   -0.72%
4889  Oct 31, 1980  1.3734  1.3734  1.3734  1.3734   -0.29%
4890  Oct 30, 1980  1.3774  1.3774  1.3774  1.3774   -0.55%
4891  Oct 29, 1980  1.3850  1.3850  1.3850  1.3850    0.38%
4892  Oct 28, 1980  1.3797  1.3797  1.3797  1.3797   -0.63%
4893  Oct 27, 1980  1.3885  1.3885  1.3885  1.3885   -0.58%
4894  Oct 24, 1980  1.3966  1.3966  1.3966  1.3966   -0.23%
4895  Oct 23, 1980  1.3998  1.3998  1.3998  1.3998    0.24%
4896  Oct 22, 1980  1.3965  1.3965  1.3965  1.3965   -0.22%
4897  Oct 21, 1980  1.3996  1.3996  1.3996  1.3996   -0.16%

[4898 rows x 6 columns]
             Date   Price    Open    High     Low Change %
0    Oct 20, 1980  1.4019  1.4019  1.4019  1.4019   -0.84%
1    Oct 17, 1980  1.4138  1.4138  1.4138  1.4138   -0.57%
2    Oct 16, 1980  1.4219  1.4219  1.4219  1.4219   -0.15%
3    Oct 15, 1980  1.4241  1.4241  1.4241  1.4241   -0.48%
4    Oct 14, 1980  1.4310  1.4310  1.4310  1.4310   -0.40%
5    Oct 13, 1980  1.4368  1.4368  1.4368  1.4368   -0.14%
6    Oct 10, 1980  1.4388  1.4388  1.4388  1.4388    0.03%
7    Oct 09, 1980  1.4384  1.4384  1.4384  1.4384   -0.05%
8    Oct 08, 1980  1.4391  1.4391  1.4391  1.4391    0.08%
9    Oct 07, 1980  1.4380  1.4380  1.4380  1.4380   -0.28%
10   Oct 06, 1980  1.4420  1.4420  1.4420  1.4420    0.55%
11   Oct 03, 1980  1.4341  1.4341  1.4341  1.4341   -0.01%
12   Oct 02, 1980  1.4343  1.4343  1.4343  1.4343   -0.16%
13   Oct 01, 1980  1.4366  1.4366  1.4366  1.4366    0.17%
14   Sep 30, 1980  1.4341  1.4341  1.4341  1.4341    0.11%
15   Sep 29, 1980  1.4325  1.4325  1.4325  1.4325   -0.38%
16   Sep 26, 1980  1.4380  1.4380  1.4380  1.4380   -0.46%
17   Sep 25, 1980  1.4447  1.4447  1.4447  1.4447   -0.01%
18   Sep 24, 1980  1.4449  1.4449  1.4449  1.4449    0.68%
19   Sep 23, 1980  1.4351  1.4351  1.4351  1.4351   -0.24%
20   Sep 22, 1980  1.4386  1.4386  1.4386  1.4386   -0.44%
21   Sep 19, 1980  1.4449  1.4449  1.4449  1.4449   -0.30%
22   Sep 18, 1980  1.4493  1.4493  1.4493  1.4493   -0.49%
23   Sep 17, 1980  1.4565  1.4565  1.4565  1.4565    0.17%
24   Sep 16, 1980  1.4541  1.4541  1.4541  1.4541    0.00%
25   Sep 15, 1980  1.4541  1.4541  1.4541  1.4541   -0.25%
26   Sep 12, 1980  1.4577  1.4577  1.4577  1.4577   -0.18%
27   Sep 11, 1980  1.4603  1.4603  1.4603  1.4603    0.14%
28   Sep 10, 1980  1.4582  1.4582  1.4582  1.4582   -0.05%
29   Sep 09, 1980  1.4590  1.4590  1.4590  1.4590   -0.03%
..            ...     ...     ...     ...     ...      ...
177  Feb 07, 1980  1.4977  1.4977  1.4977  1.4977   -0.11%
178  Feb 06, 1980  1.4993  1.4993  1.4993  1.4993    0.27%
179  Feb 05, 1980  1.4952  1.4952  1.4952  1.4952    0.19%
180  Feb 04, 1980  1.4923  1.4923  1.4923  1.4923    0.03%
181  Feb 01, 1980  1.4919  1.4919  1.4919  1.4919   -0.17%
182  Jan 31, 1980  1.4945  1.4945  1.4945  1.4945   -0.27%
183  Jan 30, 1980  1.4986  1.4986  1.4986  1.4986    0.05%
184  Jan 29, 1980  1.4979  1.4979  1.4979  1.4979   -0.09%
185  Jan 28, 1980  1.4993  1.4993  1.4993  1.4993   -0.07%
186  Jan 25, 1980  1.5004  1.5004  1.5004  1.5004   -0.15%
187  Jan 24, 1980  1.5026  1.5026  1.5026  1.5026   -0.06%
188  Jan 23, 1980  1.5035  1.5035  1.5035  1.5035    0.19%
189  Jan 22, 1980  1.5006  1.5006  1.5006  1.5006   -0.31%
190  Jan 21, 1980  1.5053  1.5053  1.5053  1.5053   -0.20%
191  Jan 18, 1980  1.5083  1.5083  1.5083  1.5083    0.06%
192  Jan 17, 1980  1.5074  1.5074  1.5074  1.5074    0.00%
193  Jan 16, 1980  1.5074  1.5074  1.5074  1.5074    0.18%
194  Jan 15, 1980  1.5047  1.5047  1.5047  1.5047   -0.42%
195  Jan 14, 1980  1.5110  1.5110  1.5110  1.5110    0.01%
196  Jan 11, 1980  1.5108  1.5108  1.5108  1.5108   -0.17%
197  Jan 10, 1980  1.5133  1.5133  1.5133  1.5133   -0.18%
198  Jan 09, 1980  1.5161  1.5161  1.5161  1.5161    0.35%
199  Jan 08, 1980  1.5108  1.5108  1.5108  1.5108   -0.40%
200  Jan 07, 1980  1.5168  1.5168  1.5168  1.5168    0.26%
201  Jan 04, 1980  1.5129  1.5129  1.5129  1.5129   -0.32%
202  Jan 03, 1980  1.5177  1.5177  1.5177  1.5177    0.18%
203  Jan 02, 1980  1.5149  1.5149  1.5149  1.5149    0.45%
204  Dec 31, 1979  1.5081  1.5081  1.5081  1.5081    0.03%
205  Dec 28, 1979  1.5076  1.5076  1.5076  1.5076    0.01%
206  Dec 27, 1979  1.5074  1.5074  1.5074  1.5074    0.41%

[207 rows x 6 columns]

In [105]:
df_eurusd = pd.concat([df_eurusd1,df_eurusd2, df_eurusd3])
df_eurusd.index.name = 'number'
df_eurusd = df_eurusd.drop(['Open', 'Change %'], axis=1)
print(df_eurusd)

                Date   Price    High     Low
number
0       Nov 21, 2018  1.1371  1.1410  1.1366
1       Nov 20, 2018  1.1372  1.1472  1.1359
2       Nov 19, 2018  1.1453  1.1467  1.1393
3       Nov 16, 2018  1.1420  1.1423  1.1320
4       Nov 15, 2018  1.1328  1.1364  1.1271
5       Nov 14, 2018  1.1310  1.1349  1.1262
6       Nov 13, 2018  1.1291  1.1296  1.1216
7       Nov 12, 2018  1.1218  1.1333  1.1214
8       Nov 09, 2018  1.1336  1.1371  1.1315
9       Nov 08, 2018  1.1363  1.1448  1.1352
10      Nov 07, 2018  1.1426  1.1502  1.1395
11      Nov 06, 2018  1.1427  1.1440  1.1389
12      Nov 05, 2018  1.1407  1.1425  1.1356
13      Nov 02, 2018  1.1387  1.1458  1.1372
14      Nov 01, 2018  1.1409  1.1426  1.1306
15      Oct 31, 2018  1.1312  1.1363  1.1301
16      Oct 30, 2018  1.1344  1.1387  1.1338
17      Oct 29, 2018  1.1373  1.1418  1.1361
18      Oct 26, 2018  1.1403  1.1422  1.1334
19      Oct 25, 2018  1.1376  1.1434  1.1355
20      Oct 24, 2018  1.1392  1.1477  1.1378
21      Oct 23, 2018  1.1471  1.1495  1.1438
22      Oct 22, 2018  1.1465  1.1552  1.1455
23      Oct 19, 2018  1.1515  1.1536  1.1433
24      Oct 18, 2018  1.1453  1.1528  1.1448
25      Oct 17, 2018  1.1501  1.1585  1.1495
26      Oct 16, 2018  1.1575  1.1623  1.1564
27      Oct 15, 2018  1.1579  1.1608  1.1537
28      Oct 12, 2018  1.1563  1.1611  1.1534
29      Oct 11, 2018  1.1594  1.1600  1.1517
...              ...     ...     ...     ...
177     Feb 07, 1980  1.4977  1.4977  1.4977
178     Feb 06, 1980  1.4993  1.4993  1.4993
179     Feb 05, 1980  1.4952  1.4952  1.4952
180     Feb 04, 1980  1.4923  1.4923  1.4923
181     Feb 01, 1980  1.4919  1.4919  1.4919
182     Jan 31, 1980  1.4945  1.4945  1.4945
183     Jan 30, 1980  1.4986  1.4986  1.4986
184     Jan 29, 1980  1.4979  1.4979  1.4979
185     Jan 28, 1980  1.4993  1.4993  1.4993
186     Jan 25, 1980  1.5004  1.5004  1.5004
187     Jan 24, 1980  1.5026  1.5026  1.5026
188     Jan 23, 1980  1.5035  1.5035  1.5035
189     Jan 22, 1980  1.5006  1.5006  1.5006
190     Jan 21, 1980  1.5053  1.5053  1.5053
191     Jan 18, 1980  1.5083  1.5083  1.5083
192     Jan 17, 1980  1.5074  1.5074  1.5074
193     Jan 16, 1980  1.5074  1.5074  1.5074
194     Jan 15, 1980  1.5047  1.5047  1.5047
195     Jan 14, 1980  1.5110  1.5110  1.5110
196     Jan 11, 1980  1.5108  1.5108  1.5108
197     Jan 10, 1980  1.5133  1.5133  1.5133
198     Jan 09, 1980  1.5161  1.5161  1.5161
199     Jan 08, 1980  1.5108  1.5108  1.5108
200     Jan 07, 1980  1.5168  1.5168  1.5168
201     Jan 04, 1980  1.5129  1.5129  1.5129
202     Jan 03, 1980  1.5177  1.5177  1.5177
203     Jan 02, 1980  1.5149  1.5149  1.5149
204     Dec 31, 1979  1.5081  1.5081  1.5081
205     Dec 28, 1979  1.5076  1.5076  1.5076
206     Dec 27, 1979  1.5074  1.5074  1.5074

[10085 rows x 4 columns]

In [106]:
df_eurusd.to_csv('mergeddata.csv')